from sage_cluster_pictures import *
T = BYTree()
T.add_blue_vertex('v1')
T.add_blue_vertex('v2')
T.add_blue_vertex('v3')
T.add_yellow_vertex('v4')
T.add_blue_vertex('v5')
T.add_blue_vertex('v6')
T.add_blue_vertex('v7')
T.add_blue_vertex('v8')
T.add_yellow_edge(('v1', 'v4', 2))
T.add_yellow_edge(('v2', 'v4', 4))
T.add_yellow_edge(('v6', 'v4', 1))
T.add_yellow_edge(('v7', 'v4', 1))
T.add_blue_edge(('v7', 'v5', 2))
T.add_yellow_edge(('v3', 'v5', 1))
T.add_yellow_edge(('v8', 'v5', 2))
sphinx_plot(T.plot(), figsize=(8,4), aspect_ratio=1)